### ISSUE TITLE
Đổi router cho truyện nhìn đẹp mắt hơn 

### ISSUE THREAD

**Issue by TranDat1114** [TranDat1114/Story-Reading#10]
![image](https://github.com/TranDat1114/Story-Reading/assets/88397960/6a9dd308-6c1d-4bef-85d1-52585542880d)

**Comment by giabao12-hali** [comment]
done 

![image](https://github.com/TranDat1114/Story-Reading/assets/73122721/3bb245bc-5c9e-4091-afbc-2734848949df)
