### ISSUE TITLE
Loại bỏ các ảnh thừa trong mục chi tiết truyện

### ISSUE THREAD

**Issue by TranDat1114** [TranDat1114/Story-Reading#13]
![image](https://github.com/TranDat1114/Story-Reading/assets/88397960/bc5eada4-83ad-41de-b762-d24e08fbc682)
 Vì truyện chữ không phải truyện tranh load ảnh lên trong các chương khiến web chậm

**Comment by giabao12-hali** [comment]
done

![Uploading image.png…]()
