### ISSUE TITLE
Thêm animation vào trang 404

### ISSUE THREAD

**Issue by TranDat1114** [TranDat1114/Story-Reading#24]

**Comment by giabao12-hali** [comment]
done 
![image](https://github.com/TranDat1114/Story-Reading/assets/73122721/766dfb1b-4ad1-4cdd-ab33-4cde0d362502)
![image](https://github.com/TranDat1114/Story-Reading/assets/73122721/39476cbb-a05c-48f3-9261-44145829cc25)
