### ISSUE TITLE
2 Component sát nhau quá Cho sì bay hay gáp zì zô ik 

### ISSUE THREAD

**Issue by TranDat1114** [TranDat1114/Story-Reading#34]
![image](https://github.com/TranDat1114/Story-Reading/assets/88397960/075f22fc-5935-4aba-a683-9864c2212123)

**Comment by giabao12-hali** [comment]
done 
![image](https://github.com/TranDat1114/Story-Reading/assets/73122721/887daff8-3d7e-481d-bbf1-381251417fc6)
